# Welcome to numpy #

In [1]:
import numpy as np

In [2]:
myArr = np.array([2,3,2,1], np.int64)

In [3]:
myArr

array([2, 3, 2, 1])

In [4]:
myArr.shape

(4,)

In [5]:
myArr.dtype

dtype('int64')

# Array declaration in Numpy 

In [6]:
import numpy as np
listArray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [7]:
listArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
listArray.dtype

dtype('int64')

In [9]:
listArray.shape

(3, 3)

In [10]:
listArray.size

9

In [11]:
zeros = np.zeros((4,5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
zeros.shape

(4, 5)

In [14]:
zeros.size

20

In [15]:

zeros.dtype

dtype('float64')

In [16]:
rngArr = np.arange(12)

In [17]:
rngArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
rngArr.shape

(12,)

In [19]:
lspace = np.linspace(1,5, 4)

In [20]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [21]:
emptyArr = np.empty((3,4))

In [22]:
emptyArr

array([[1.29109051e-311, 3.01380044e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 1.16095484e-028, 2.66913348e+007,
        5.28595592e-085],
       [2.93625480e-062, 2.59027849e-144, 4.82412328e+228,
        1.04718130e-142]])

In [23]:
identity = np.identity(40)

In [24]:
identity

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(40, 40))

In [25]:
identity.size

1600

In [26]:
arr = np.array([[2,3,1],[2,2,1],[5,3,3]])

In [27]:
arr

array([[2, 3, 1],
       [2, 2, 1],
       [5, 3, 3]])

In [28]:
arr.sum(axis= 0)

array([9, 8, 5])

In [29]:
arr.sum(axis = 1)

array([ 6,  5, 11])

* Transpose 

In [30]:
arr.T

array([[2, 2, 5],
       [3, 2, 3],
       [1, 1, 3]])

In [31]:
it = arr.flat

In [32]:
for it in arr.flat:
    print(it)

2
3
1
2
2
1
5
3
3


In [33]:
arr.ndim

2

In [34]:
arr.nbytes

72

In [35]:
identity.nbytes

12800

In [36]:
arr.argmax()

np.int64(6)

In [37]:
myArr.argmax()

np.int64(1)

In [38]:
one = np.array([3,1,6])

In [39]:
one

array([3, 1, 6])

In [40]:
one.argmax()

np.int64(2)

In [41]:
one.max()

np.int64(6)

In [42]:
one.min()

np.int64(1)

In [43]:
one.argsort()

array([1, 0, 2])

In [44]:
arr.argmin()

np.int64(2)

In [45]:
arr

array([[2, 3, 1],
       [2, 2, 1],
       [5, 3, 3]])

In [46]:
arr[0,2] = 0

In [47]:
arr

array([[2, 3, 0],
       [2, 2, 1],
       [5, 3, 3]])

In [48]:
arr.argmin()

np.int64(2)

In [49]:
arr.argmax()

np.int64(6)

In [50]:
arr.argmin(axis = 0)

array([0, 1, 0])

In [51]:
arr.argsort()

array([[2, 0, 1],
       [2, 0, 1],
       [1, 2, 0]])

In [52]:
arr.argsort(axis = 1)

array([[2, 0, 1],
       [2, 0, 1],
       [1, 2, 0]])